/**
 * @packageDocumentation
 * @module api.functional.report.template.upload
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IReport } from "../../../../structures/report/IReport";

/**
 * Upload and parse template file
 * @controller ReportController.uploadTemplate
 * @path POST /report/template/upload
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function uploadTemplate(
  connection: IConnection,
  body: uploadTemplate.Body,
): Promise<uploadTemplate.Output> {
  return true === connection.simulate
    ? uploadTemplate.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...uploadTemplate.METADATA,
          template: uploadTemplate.METADATA.path,
          path: uploadTemplate.path(),
        },
        body,
      );
}
export namespace uploadTemplate {
  export type Body = IReport.ITemplateUpload;
  export type Output = { templateId: string; template: IReport.ITemplate };

  export const METADATA = {
    method: "POST",
    path: "/report/template/upload",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/report/template/upload";
  export const random = (): {
    templateId: string;
    template: IReport.ITemplate;
  } => typia.random<{ templateId: string; template: IReport.ITemplate }>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
