/**
 * @packageDocumentation
 * @module api.functional.report.template
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as upload from "./upload";
